name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  vitest:
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: "test-secret-for-ci-only"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm -w install
      - name: Test with coverage
        run: pnpm -w vitest run --coverage
      - name: Upload coverage to Codecov (patch only)
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          flags: patch
          disable_search: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


